name: yolov11-cfruit
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - numpy>=1.24.0
  - pillow>=10.0.0
  - opencv>=4.8.0
  - pyyaml>=6.0
  - tensorboard>=2.13.0
  - tqdm>=4.65.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pandas>=2.0.0
  - requests>=2.31.0
  - pytest>=7.4.0
  - pip:
    - albumentations>=1.3.0
    - timm>=0.9.0
    - thop>=0.1.0
    - black>=23.0.0
    - flake8>=6.0.0 