# YOLOv8-CFruit 模型配置
model:
  # 主干网络配置
  backbone:
    type: 'cspdarknet'
    depth_multiple: 1.0
    width_multiple: 1.0
    cbam: true
    cbam_ratio: 16
    activation: 'silu'
    
  # 颈部网络配置
  neck:
    type: 'panet'
    depth_multiple: 1.0
    width_multiple: 1.0
    transformer: true
    transformer_heads: 8
    transformer_dim: 256
    activation: 'silu'
    
  # 头部网络配置
  head:
    type: 'anchor_free'
    num_classes: 1
    reg_max: 16
    activation: 'silu'

# 训练配置
training:
  epochs: 300
  batch_size: 16
  img_size: 640
  device: 0
  
  # 优化器配置
  optimizer:
    type: 'adam'
    lr: 0.001
    weight_decay: 0.0005
    
  # 学习率调度器
  scheduler:
    type: 'cosine'
    warmup_epochs: 3
    warmup_lr: 0.0001
    
  # 损失函数权重
  loss_weights:
    cls: 0.5
    box: 7.5
    dfl: 1.5

# 数据增强配置
augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0 